### ISSUE TITLE
Handle `rmdir` of empty directories when moving or deleting last password from a directory

### ISSUE THREAD

**Issue by nokernel** [gopasspw/gopass#1009]
### Summary

Handle `rmdir` of empty directories when moving or deleting last password from a directory.

### Steps To Reproduce
With this passwords structure
```bash
myname1
    |
    ----myname1
myname2
   |
   ----myname2
```

Do
```bash
gopass mv myname1/myname1 myname2/myname1
gopass mv myname2/myname1 myname1
Error: failed to save secret 'myname1': a folder named myname1 already exists
```

### Expected behavior
gopass shall remove empty directories when moving/deleting last password in a directory.

### Environment

- OS: Linux
- OS version: Ubundu 18.04
- gopass Version: gopass 1.8.3-git+HEAD go1.11.2 linux amd64
- Installation method: go build

### Additional context
This is happening since 1st public version of gopass released.

**Comment by espoelstra** [comment]
It would also be great if it prevented or at least warned when a folder was being created with the same name as an entry. I just ran into the case where `echo foo | gopass insert secret/somesite` and then doing `echo bar | gopass insert secret/somesite/nestedsecret` creates a folder alongside the `secret/somesite` entry. That's all good since I can access either with their full path, but then attempting `gopass edit secret/somesite` and trying to save the changed entry file FAILS, due to it being a "folder" and not a file somehow in that flow.
I also tried to `gopass mv secret/somesite/nestedsecret secret/nestedsecret` and then editing the first entry again, but as stated in this issue, the directory remains.
