### ISSUE TITLE
Failed to decrypt on Firefox addon

### ISSUE THREAD

**Issue by kleewho** [gopasspw/gopass#1037]
I've been using `gopass` for few months already. Unfortunately I'm not sure since when but `gopass bridge` is failing with `failed to get secret: Failed to decrypt`. I don't recall playing with gpg lately. The `gopass` cli client works fine, and `gopass bridge` in Chromium works fine as well. Can't figure out what might be the problem or how to fix that. I'd be happy if someone could help.

Versions:
* gopass 1.7.2 (39fb91ab96c8ba59b67c33d6b938a474dcbb5000) go1.10 linux amd64
* Mozilla Firefox 63.0
* gopass bridge 0.4.0, last updated November 5, 2018
* Ubuntu 18.04
* gpg (GnuPG) 2.2.4
* libgcrypt 1.8.1

**Comment by martinhoefling** [comment]
@kleewho, can you provide a store with a minimum working example?

**Comment by Pharb** [comment]
```shell
➜  gopass list --flat | grep github.com
websites/github.com/
➜  gopass mounts
No mounts
➜  echo '{"type":"query", "query": "github"}' | ./test-client | gopass jsonapi listen
["websites/github.com/test"]
➜  echo '{"type":"getLogin","query":"websites/github.com/test"}' | ./test-client | gopass jsonapi listen
D{"error":"failed to get secret: Entry is not in the password store"}
➜  gopass websites/github.com/test # Pinentry is opened, error when pinentry cancelled. Works when pinentry completed successfully.
gpg: decryption failed: No secret key

Error: failed to retrieve secret 'websites/github.com/test': Failed to decrypt
```

My first suspicion was that something related to pinentry is not handled correctly by `gopass jsonapi`.

```shell
➜  export GOPASS_DEBUG=true
➜  gopass websites/github.com/test
[DEBUG] Root Store initialized with URL gpgcli-gitcli-fs+file:///Users/tng/.password-store
[DEBUG] fs.Exists(.gpg-id) - /Users/tng/.password-store/.gpg-id
[DEBUG] Store is already initialized
[DEBUG] fs.Isdir(websites/github.com/test) - /Users/tng/.password-store/websites/github.com/test -> false
[DEBUG] fs.Isdir(websites/github.com/test) - /Users/tng/.password-store/websites/github.com/test -> false
[DEBUG] fs.Exists(websites/github.com/test.gpg) - /Users/tng/.password-store/websites/github.com/test.gpg
[DEBUG] fs.Get(websites/github.com/test.gpg) - /Users/tng/.password-store/websites/github.com/test.gpg
[DEBUG] gpg.Decrypt: /usr/local/bin/gpg [/usr/local/bin/gpg --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --decrypt]
# Pinentry is opened and successfully completed
[DEBUG] decodeKV() - simple KV
# Secret is correctly decoded and printed
```

```shell
➜  echo '{"type":"getLogin","query":"websites/github.com/test"}' | ./test-client | gopass jsonapi liste
[DEBUG] Root Store initialized with URL gpgcli-gitcli-fs+file:///Users/tng/.password-store
[DEBUG] fs.Exists(.gpg-id) - /Users/tng/.password-store/.gpg-id
[DEBUG] Store is already initialized
[DEBUG] fs.Get(.gpg) - /Users/tng/.password-store/.gpg
[DEBUG] File .gpg not found: open /Users/tng/.password-store/.gpg: no such file or directory
D{"error":"failed to get secret: Entry is not in the password store"}
```

```shell
➜  echo '{"type":"getLogin","entry":"websites/github.com/test"}' | ./test-client | gopass jsonapi listen
[DEBUG] Root Store initialized with URL gpgcli-gitcli-fs+file:///Users/tng/.password-store
[DEBUG] fs.Exists(.gpg-id) - /Users/tng/.password-store/.gpg-id
[DEBUG] Store is already initialized
[DEBUG] fs.Get(websites/github.com/test.gpg) - /Users/tng/.password-store/websites/github.com/test.gpg
[DEBUG] gpg.Decrypt: /usr/local/bin/gpg [/usr/local/bin/gpg --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --decrypt]
# Pinentry is opened and successfully completed
[DEBUG] decodeKV() - simple KV
# Secret is correctly decoded and returned as JSON
```

So one problem here actually is that `gopass jsonapi listen` will use an empty string when the `"entry"` key is missing from the message, which made debugging this issue a bit confusing.

@kleewho Could you please try the debugging command again with `'{"type":"getLogin","entry":"github.com"}'` instead of `'{"type":"getLogin","query":"github.com"}'`? And if you still see the same error, could you please run it with `export GOPASS_DEBUG=true` and take a look at the log output? You can also post some of the debug logs here, but please check that there is not any sensitive information in them, that you might want to keep private. It might also be helpful to try these commands with `GOPASS_DEBUG=true`:

- `gopass list --flat`
- `echo '{"type":"queryHost","query":"github.com"}' | ./test-client | gopass jsonapi listen`
- `echo '{"type":"query","query":"github.com"}' | ./test-client | gopass jsonapi listen`

**Comment by kleewho** [comment]
> @kleewho, can you provide a store with a minimum working example?

Working or not working you mean?

**Comment by Pharb** [comment]
Maybe related? https://github.com/gopasspw/gopassbridge/issues/22#issuecomment-462453901

**Comment by eFFeeMMe** [comment]
Hello everyone, I'm getting the same error.

Gopass Bridge worked fine upon first installing it, but stopped working by the next reboot. Gopass CLI works perfectly.

Versions:
* ubuntu 19.04
* gopass 1.8.4
* firefox 68.0
* gopass bridge 0.5.1
* libgcrypt 1.8.4
* gpg 2.2.12-1ubuntu3

**Comment by Pharb** [comment]
@eFFeeMMe Can you please try to provide the debugging info described in this comment: https://github.com/gopasspw/gopass/issues/1037#issuecomment-451760918

Usually this problem is caused by having different environment variables when the script (installed by `gopass jsonapi configure`) is called by your browser vs. when you call `gopass` yourself in an interactive shell.

**Comment by eFFeeMMe** [comment]
@Pharb thanks for your kind response, I executed `gopass jsonapi configure` again and that did the trick.

It was probably just some installation fluke on my part. Perhaps the issue was that the configuration script wasn't even being run therefore I had no gopass client listening.

Just for reference, the commands' output I was getting was:
```
fm@fm:~/repos/gopassbridge/test-client$ echo '{"type":"getLogin","query":"github.com"}' | ./test-client | gopass jsonapi listen
D{"error":"failed to get secret: Entry is not in the password store"}
fm@fm:~/repos/gopassbridge/test-client$ echo '{"type":"getLogin","entry":"Account/github.com"}' | ./test-client | gopass jsonapi listen
R{"username":"yep it worked","password":"yep it worked"}
```

(versions same as above)

**Comment by torfmaster** [comment]
I am also having this issue, however I get much less (binary) output from the debug commands:
```
00000000: 0200 0000 5b5d                           ....[]
```
My versions are:
Ubuntu 18.04
gpg (GnuPG) 2.2.4
Firefox 76.0.0.1
gopassbridge 0.7.0
gopass 1.8.6

gopass itself is working fine but it would be nice if it would work inside Firefox.
