### ISSUE TITLE
Investigate usage of gopenpgp.org libs

### ISSUE THREAD

**Issue by metalmatze** [gopasspw/gopass#1114]
Today @dominikschulz posted https://gopenpgp.org/ and the project looks really interesting. gopass might even be the prime use case for this.

Thoughts?

**Comment by dominikschulz** [comment]
For me GPG is a dead end. Too complex to be secure, too hard to use from scritpts.
I don't see how this could be fixed without rewriting GPG to something entirely different.
GPG might have it's usecases still, but as a backend for a password store it's likely not the best choice.

I plan to investigate more modern and sane cryptographic choices but won't spend any more time than necessary on GPG.

If someone cares about GPG and is able to dedicate considerable and consistent effort on it, then we can try to keep supporting GPG. But otherwise it will eventually be removed from gopass. (I will stop supporting GPG once I have found a viable alernative and at that point it will detoriate to the point where it's too dangerous to keep it in)
