### ISSUE TITLE
Second line of yaml file is indented wrongly 

### ISSUE THREAD

**Issue by combor** [gopasspw/gopass#1121]
### Summary
Yaml indentation is broken while using gopass.

### Steps To Reproduce
```
$ pass test
a:
  b:
    c: d
$ gopass test
a:
b:
    c: d
```

All indentation is done with double white space. It's just second line that looses two spaces. 

### Expected behavioUr

Both outputs look same

### Environment

- OS:  Mac OS X High Mojave,
- OS version: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.8.5-git+HEAD go1.12.5 darwin amd64
<root>     - gpg 2.2.16 - git 2.21.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
- Installation method:  from source

**Comment by combor** [comment]
I think it's still a bug

**Comment by combor** [comment]
This is still a bug.

**Comment by combor** [comment]
This is still a bug.

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.

Unfortunately this isn't easy to fix, due to the way we handle secrets.
We apply multiple heuristics and assumptions about secrets to support some more advanced features, e.g. we support YAML as well as simple Key/Value semantics and handle the first line of a secret in a special way (this is usually the password).

While there is no easy fix, the workaround for proper YAML handling is to prefix a secret containing YAML with an empty line and three dashes: ---.

While this is probably not what you were looking for, this report is still very much appreciated and is good input for our considerations how we might interpret secrets in the future, e.g. apply no heuristics at all or enforce a strict format.

**Comment by dominikschulz** [comment]
I won't attempt to fix this as is.
It should be eventually covered by the linked issue.
