### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by bijang** [gopasspw/gopass#1265]
I hate to ask but is this project actively maintained? The commit activitiy is infrequent and the features state on the table of the main github page seems static, is it up to date still? many thanks for your works on this project and hope you are all staying safe

**Comment by martinhoefling** [comment]
First of all: Yes, gopass is still actively maintained (and used) by several people. It is true that the commit frequency has declined but this is also due to the fact that most commonly requested features are implemented.
We would be happy to see contributions, in case you think a cruicial feature is missing or just not properly documented. Reach out via a github issue, if there are questions, if or how to implement those. 
Furthermore, several projects evolve around (the more 'static' core 'gopass'), like gopassbridge or gopass-ui.
Next steps in the development of gopass are improving the windows support, but also others are on the list.

**Comment by dominikschulz** [comment]
We're actively using gopass and commited to fix any critical issue in time.
However capacity to do feature development is quite limited.
