### ISSUE TITLE
Memorable password length is incorrect

### ISSUE THREAD

**Issue by tomkel** [gopasspw/gopass#1392]
### Summary
Generating a memorable password will produce a password that is not equal to the given length

```
> gopass generate -m -s test 10

confirm8?nuclear1)
siren5?wide5~
ensure6$apology9[
```

### Expected behavior
The total length will be equal to 10

### Environment
- OS: Mac OS Catalina
- OS version: 10.15.4
- gopass Version: 1.9.2
- Installation method: brew

Thanks again for your work on this project!

**Comment by tomkel** [comment]
Relevant PR https://github.com/gopasspw/gopass/pull/1351

**Comment by dominikschulz** [comment]
Hi,

thanks for your report.

Actually this is intentional. It would be very awkward to generate a memorable password of exactly the requested length, since we can't just truncate the password.

The documentation doesn't exactly specify how the length parameter is used, so I guess we could clarify that.

Given that I don't think this is a bug, but a feature request: Do you have any specific requirement that the password has to be of exactly the specified length?

**Comment by tomkel** [comment]
No, I don't! If that's the intent , then it's fine with me if it's clarified either in the  `-h` text or somewhere else. Thanks!
