### ISSUE TITLE
Cannot find password store, instead creates a gpgcli-gitcli-fs+file:/ directory in the working directory

### ISSUE THREAD

**Issue by ondrik** [gopasspw/gopass#1561]
### Summary
Hi! Many thanks for providing this great password manager! From a few days ago, I've started having the following issue.

Since gopass 1.10.0, gopass seems it cannot find the password store in `~/.password-store`. Instead, it creates the directory `gpgcli-gitcli-fs+file:/` in the current directory.

### Steps To Reproduce
In an empty directory:
```
$ ls
$ gopass
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: q
$ ls
gpgcli-gitcli-fs+file:/
```

### Environment

- OS: Mac OS X Catalina
- OS version: 19.6.0 Darwin Kernel
- gopass Version: 1.10.0, 1.10.1
- Installation method: brew

### Additional context
Content of `~/.config/gopass/config.yml`:
```{yaml}
root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///Users/ondra/.password-store
  recipient_hash: {}
  safecontent: true
  usesymbols: false
mounts: {}
version: 1.8.1
```

**Comment by dominikschulz** [comment]
Uh oh, that sounds like a config migration bug. The old scheme prefix should be automatically stripped.
Thanks for reporting and providing a copy of your config. Will use that in an attempt to reproduce.

**Comment by jonathanrohland** [comment]
@dominikschulz I ran into this problem as well and would like to help writing a fix (or maybe add an appropriate warning). However, I'm not sure what your plan going forward with this is. I took a look into the code but since I'm not familiar with the project yet it's quite likely that I haven't found every relevant piece of code. If I understood it correctly the problem occurs because the config-value for the path previously used to contain the prefix `gpgcli-gitcli-fs+file://`, but now it doesn't anymore.
Introducing a legacy-config-type (as in `config/legacy.go`) doesn't seem like a viable solution, since the format of the config hasn't actually changed (only the format of the expected value).

I can see a few ways out of this:
* Checking the config on load and logging a warning (+exiting) when the obsolete prefix is found.
* Checking the config on load and dropping the prefix (either silently or with a warning message)
* Checking the config and fixing it on disk (seems quite intrusive to me, but I'm mentioning it for completeness)

Is any of these desirable and would you want help fixing it?
Or is there any other config migration code that I didn't find in my research?

**Comment by dominikschulz** [comment]
@jonathanrohland Thanks for offering to help!

What we're currently doing is this: https://github.com/gopasspw/gopass/blob/master/internal/config/legacy.go#L124
That is, dropping the prefix on load.

However in this case it doesn't seem to work. I guess the config is wrongly detected as another version which doesn't apply this step. With the provided example it should be easy to reproduce, but I didn't have the time to do that, yet.

**Comment by jonathanrohland** [comment]
Hello @dominikschulz, thanks for pointing me in the right direction. I think I found the issue and opened a PR for this.
I hope this is conforming with the project's standards, at the very least I learnt a lot about Go and your project guidelines in the process :-)

**Comment by dominikschulz** [comment]
Oh, thanks for that PR. So it looks like this did never actually work? That's a little embarrassing. I guess we should also have some tests covering this. But the fix should be fine as is.
