### ISSUE TITLE
: (colon) not allowed in username

### ISSUE THREAD

**Issue by jaceq** [gopasspw/gopass#1586]
### Summary
I am trying to add a username which contains a colon ( : ) and it does not get accepted (this is username for external service and we cannot change it in a way to get removed a colon.

### Steps To Reproduce
run: 
gopass insert "/test/user:name"

error:
Error: Usage: gopass insert name

### Expected behavior
I expect it to accept it and add to store.

### Environment
gopass --version
gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 linux amd64

- OS: Ubuntu 20.04
- OS version: 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 linux amd64
- Installation method: apt repo from

**Comment by AnomalRoil** [comment]
I think this is currently supported using the key-value way only:

You need a name for your entry without the username in it and then you need to do:
`gopass insert /test/nameofentry username` and type the name with the colon there.

Doing so is notably compatible with gopass bridge I think

**Comment by dominikschulz** [comment]
Yes, I think so, too. Since gopassbridge expects the username to be part of the path and - by default - we use the filesystem to store secrets, this is something we likely can't properly fix (although the error message should be better).

This would work with the fully encrypted backend - but that's nothing more than a proof of concept, yet.

**Comment by jaceq** [comment]
Thx for answers. 
Now, while usging advice from @AnomalRoil works, so `gopass insert /test/entry "user:name"` get accepted but then when I do just `gopass` I do not see it on the list... 
As the same time when I try to add it again, I get into that it already exists.

**Comment by dominikschulz** [comment]
If you add a key to an entry you won't see it listed with e.g. `gopass ls`.
But when you do `gopass show test/entry` or `gopass show test/entrz user` you should get what you did insert.

**Comment by jaceq** [comment]
@dominikschulz is this a bug or design? and if it's design why is it like this? It's a bit confusing to be honest.

**Comment by dominikschulz** [comment]
This by design.

`gopass` has secrets, like other password store implementations, these map to encrypted files. This is what you see with `gopass ls`.

`gopass` also supports key value pairs inside these secrets. Those keys can only be seen when you decrypt a secret. By design we don't decrypt any secret unless strictly necessary. So `gopass ls` can't show the keys.

**Comment by dominikschulz** [comment]
Is this issue fixed by #1610 , too?

**Comment by jaceq** [comment]
It seems so! Thx!
