### ISSUE TITLE
multiline entry get scrambled

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1600]
### Summary

I'm having a weird behavior when using gopass for inserting multiline content containing curly brackets.
For some reason, the secret saved during insertion produces a different output when shown.

This could be related to my setup but do gopass edit/parse what's being inserted in some way that could
produce below changes?

### Steps To Reproduce

start inserting a new entry
```bash
$ echo $EDITOR                   
vim
$ gopass insert -m test
```

Insert the following:
```
test1
test2
{
  "Creator": "the creator"
}
```

try to read back the entry:
```bash
$ gopass show test
test1
"Creator": "the creator"
test2
{
}
```

### Expected behavior

Entry content is exactly the same as inserted.

### Environment

- OS: linux
- gopass Version: 1.10.1

**Comment by deadc0de6** [comment]
It seems gopass tries to parse ([mime - yaml - kv - plain](https://github.com/gopasspw/gopass/blob/master/pkg/gopass/secret/secparse/parse.go)) and for some reason the above entry get matched into *kv*. Is it possible to force gopass to treat the entry as plain (in other words only expect the first line to be the password and handle the rest as *raw*)?

**Comment by AnomalRoil** [comment]
Mhhh, looks like my fix for #1573 and #1582 is the culprit. 

@dominikschulz we really need to define the different secret format and document correctly how `insert` is supposed to behave.
Fixing the way insert works is only possible if we know how we want it to work.

That being said, I like the workaround of just having a flag that prevents any parsing.

**Comment by AnomalRoil** [comment]
Actually this is really annoying, not just for insert.

Currently when we `show` a secret with for example:

```
secr3tp4ss
admin: alice

mysql-user: bob
url: //dburl.com/db
password: oth3rp4ss

REST API: 
url: //example.com/rest
```

Because of the parsing plus the sorting of the keys we'll end up with:
```
secr3tp4ss
REST API: 
admin: alice
mysql-user: bob
password: oth3rp4ss
password: oth3rp4ss
url: //example.com/rest


```

After having patched #1601 we'll end up with:
```
secr3tp4ss
REST API: 
admin: alice
mysql-user: bob
password: oth3rp4ss
password: oth3rp4ss
url: //example.com/rest
url: //dburl.com/db

``` 
Which isn't really better IMO.

**Comment by dominikschulz** [comment]
Do you see any way how we could improve this before we have fully fleshed out how it should work?
Should disable the new parser for the time being?

**Comment by dragetd** [comment]
Among 4-5 other gopass users I know, everyone kind of expected the format to be always plain with the exception of special lines like 'login: xxx' or 'url: xxx' and the password in the first line. In contrast, at least two were just as surprised as me when it suddenly started reordering lines and parsing different formats.

Is there some PR, ossue, discussions of some sort of the reasoning behind this change? Why would I want to specify the format of my secret? Of course I could format secrts as JSON, but since they are passed via pipes in most cases, the MIME type is lost anyways. Saving them as plain always worked anyways. I'd love to hear why this was changed at all.

**Comment by OJFord** [comment]
I was about to open a duplicate, I initially thought leading whitespace was being stripped (just adding some keywords for other searchers :wink:) but then realised actually it's not that simple - that does happen, but not always (`echo -e 'a\n    b' | gopass insert -m` does not reproduce, for example), and the reordering mentioned also confuses it.

I noticed because I store my work kubeconfig.yaml in pass, and switched to gopass (all initially seeming well) over the weekend.

Obviously, whitespace is important for YAML, and the reordering further means that object/array entries are not where they should be.

**Comment by OJFord** [comment]
Testing pass compatibility (#1622) would also be blocked on this / have caught this.

**Comment by AnomalRoil** [comment]
So this is going to be solved in two phases:

1. We will stop parsing secrets in 1.10.2 and add a flag to generate/insert/edit in order to create Mime secret for those who still want Mime secrets
2. We will refactor and clean up our secret formats and how we handle input and parsing in 1.11

We need to make sure we add a regression test in 1.10.2 to avoid having the same problem in 1.11.

**Comment by AnomalRoil** [comment]
The new flag `-n` allows to disable parsing when using `show`, and the new option `parsing` allows to completely disable parsing of output (but then KV and Yaml entries won't work.)

Notice input is not parsed at all anymore, only output is, so the entry's content should always match what you've typed as input now :D
