### ISSUE TITLE
-dmenu stopped working with rofi

### ISSUE THREAD

**Issue by mordax777** [gopasspw/gopass#1647]
### Summary
Before I updated my Gopass to the latest version, i used it with Rofi to get my secrets out of the store with the following command: `gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty gopass show -c`. But recently it stopped working and I dont know if it is a issue with Rofi or Gopass.

### Steps To Reproduce
* Install Rofi and Gopass with latest version
* Write `gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty gopass show -c` into your console

### Expected behavior
Rofi menu with a list of your secrets

### Environment

- OS: Arch
- OS version: Linux 5.9.4-arch1-1 #1 SMP PREEMPT Wed, 04 Nov 2020 21:41:09 +0000 x86_64 GNU/Linux
- gopass Version: gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64
- Installation method: Arch Community Repo

**Comment by AnomalRoil** [comment]
Tested on Rofi 1.5.0 : it works.

I'm going to try to install the latest rofi from git since it seems they've recently released 1.6 and 1.6.1.

**Comment by mordax777** [comment]
@AnomalRoil can you please share your command. I dont get it to run.

**Comment by AnomalRoil** [comment]
I'm trying with the same command as you:

Let's check which version we are running: 

Rofi compiled from latest release on Github:
```
$ rofi -v
Version: 1.6.1
```

Gopass from Github since I think that Arch is compiling from Github instead of using the release:
```
$ gopass -v
gopass 1.10.1+93539afc (93539afc 2020-11-27 13:09:44) go1.15.5 linux amd64
```

When running your command, I get a dmenu prompt:
```
gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty gopass show -c
```
I also tried with v1.10.1 instead of git tip and it's also working.

What desktop environment are you running? Could it be your Windows Manager that's not displaying Rofi menu?
Is your Gopass password store populated and working in the CLI?

- [ ] If you run `gopass ls --flat`, does it display the list of your secrets?
- [ ] If you run `rofi -dmenu`, does it display an empty Rofi prompt?

**Comment by mordax777** [comment]
Rofi:
```
rofi -v
Version: 1.6.1
```
Gopass
```
gopass -v
gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64
```
_If you run gopass ls --flat, does it display the list of your secrets?_
Yes

_If you run rofi -dmenu, does it display an empty Rofi prompt?_
If I run it with `-dmenu` or without, the result is the same, I see `rofi` in `combi` mode(both opened and closed applications).

When trying to use the Wayland alternative to rofi https://hg.sr.ht/~scoopta/wofi it seems to work again. So maybe it is a rofi porblem?

**Comment by AnomalRoil** [comment]
Yes, this looks like a Rofi issue.
