### ISSUE TITLE
autoclip for `gopass show`

### ISSUE THREAD

**Issue by slokhorst** [gopasspw/gopass#1764]
The current usage for `gopass show` is:
* default: show the password
* if the `-c` option is used: copy the password to the clipboard

However, 9/10 times I want to clip the password and not show it. So it would be nice if there was a config option to clip by default.

It looks like this option was removed in #1502, because it shared the same configuration option as was used for `gopass generate`. I'm not sure why this was a problem, but if it is, we could maybe split it into two options? `autoclip-show` and `autoclip-generate` (alias `autoclip` for backwards compatibility).

**Comment by dominikschulz** [comment]
Maintaining config options is very time consuming so we're trying to remove config options instead of adding new ones.
Also the implementation of `show` already has a lot of corner cases which are hard to get right. Especially `autoclip` for show led to a flood of complaints so I'd be very careful to bring it back.

If someone were to create a comprehensive PR covering implementation, documentation, specification and tests we might accept it. Otherwise this is unlikely to happen.

**Comment by stefan2904** [comment]
I have the same "issue" when it comes to using gopass without a command, so just `gopass websites/github.com` (which might be an "alias" to `show`?). Until a recent update I installed, this copied the password into the clipboard, and did not display it. 

The `--help` documentation reads:

`  --clip, -c                 Copy the password value into the clipboard (default: false)`

I get that `autoclip` is the wrong option for this, as [the documentation states](autoclip):

` Always copy the password created by gopass generate. Only applies to generate.`

I was also confused about how to change this default ...

---

Btw, I was also a bit confused since this behavior suddenly changed. I assume this was a result of #1488?
(Context: I used the apt repository until last week and apparently missed some updates until now by doing so.)
