### ISSUE TITLE
insert and create behave differently

### ISSUE THREAD

**Issue by warden** [gopasspw/gopass#1811]
### Summary

When I look at gopass help, I don't see a good description of a difference between *insert* and *create* commands.
But when I use it, I get confused:

```
gopass insert a/b/c

result:

gopass
├── a/
│   └── b/
│       └── c
```

```
gopass create a/b/c

result:

gopass list

├── misc/
│   └── a_b_c

```

For me the second thing is a bug or at least the behavior is undocumented.

### Expected behavior
 
I expect the slashes to be always treated as folder structure.

### Environment

```
gopass 1.11.0 go1.15.6 darwin amd64
```

**Comment by dominikschulz** [comment]
Hmm, `create` is designed to be more opinonated than the other commands.
It's supposed to be called without arguments and provide an interactive session to guide the user through creating a secret in a standard location. Think of rather unexperienced users.

I think the proper way to address this issue would be to make `gopass create` stop accepting any path arguments.

**Comment by WPettersson** [comment]
> I think the proper way to address this issue would be to make `gopass create` stop accepting any path arguments.

This would technically fix this issue as specified, but one thing that does annoy me (and the reason I subscribed to this issue) is that the guided approach of `gopass create` will still replace slashes with underscores and put it in the generic folder if I create a generic secret. I'd like to be able to add secrets to e.g. `finance/bank-A/mortgage` using `gopass create` without gopass putting this into `generic/finance_bank-A_mortgage`.

I see a few ways of achieving this:
* If there is a slash in a name, have `gopass create` ask the user for a Y/N to use the specified folder structure
* Add a configuration or command line option that will use the given folder structure instead of doing any replacing
* Add another "type" of secret, alongside website, PIN, and generic, which allows the exact specification of secret location.

Some of the above solutions would also solve this issue.

**Comment by dominikschulz** [comment]
You are probably aware of `gopass edit -c` and `gopass insert`, aren't you? These are basic commands that should behave similar to `pass insert`. These are unguided and shouldn't translate anything.

`gopass create` on the other hand is designed to offer a guided approach. I really don't want to support any sophisticated nesting with `gopass create`. One can always use `gopass edit` for that.

* Adding a config option carries significant maintenance overhead, so this is not something I'd like to do
* And we already have a lot of user input questions so I'd rather not add another one
* We could consider adding a command line flag to not mess with the user supplied path
* Or maybe add a "custom" type which allows an arbitrary path

**Comment by warden** [comment]
> We could consider adding a command line flag to not mess with the user supplied path

My view is that:
- both commands should behave consistently
- _by default_ they should not mess with the path, i.e. if I provide a/b/c it should go in folders, any non '/' should be treated as path entry for the root folder

**Comment by WPettersson** [comment]
Yes, I am aware of `gopass edit -c` and `gopass insert`. I am specifically looking for a guided technique that doesn't translate names. However, I do totally realise the overheads involved with maintaining more code for any of my suggested solutions. I don't know if anyone else fits into my particular use-case, but if there is no real need for such support, I won't be upset if you go ahead with the original fix. I can probably adjust the way I use gopass to find a different solution, probably just learning to use `gopass generate` and remembering the command line options.

**Comment by dominikschulz** [comment]
At this point I really don't want to change the default.
This is potentially too disruptive.

But adding a command line flag, e.g. -f, is something I'll consider doing.

**Comment by dominikschulz** [comment]
Adding a flag should be fine here. I'm working on that.

But the implementation of the create command is not in good shape. This will take a bit.
