### ISSUE TITLE
`fscopy` and `fsmove` are not shown in the help

### ISSUE THREAD

**Issue by pdecat** [gopasspw/gopass#1831]
### Summary

The `fscopy` and `fsmove` subcommands are not shown in the command line help.
I've seen the warning about these commands being moving targets: https://github.com/gopasspw/gopass/blame/v1.12.1/docs/features.md#L309
Is this intentional?

### Steps To Reproduce

```
gopass help
```

### Expected behavior

`gopass help` should show the `fscopy` and `fsmove` commands.

### Environment

- OS: Ubuntu 20.10
- OS version: `Linux myhost 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.12.1-git+HEAD go1.16 linux amd64`
- Installation method: from source

### Additional context

N/A

**Comment by dominikschulz** [comment]
For the time being this is intentional.

We have a few commands that were added without a solid plan and where we're not sure if or how we want to support them going forward.

So I thought the least disruptive way to discourage their use would be to hide them.

Feel free to make an argument to remove them or make a case to keep them. In the latter case I'd kindly ask for some help with polishing them.

**Comment by pdecat** [comment]
Please keep them :pray: 

My use case with `fscopy` is to securely store some configuration files containing sensitive information, keystores and private keys.

**Comment by dominikschulz** [comment]
At this point there are no plans to remove them.
But before I unhide them we'll need a better "story" (use case, docs, maybe tests) around them.

**Comment by bozerkins** [comment]
Here's what currently available on how to use those commands
https://github.com/gopasspw/gopass/blob/master/docs/features.md#support-for-binary-content
