### ISSUE TITLE
gopass setup can't be used for unattended setup

### ISSUE THREAD

**Issue by jensklose** [gopasspw/gopass#1873]
### Summary
The version 1.12.4 fixed the --yes parameter error thrown, but the setup function is still broken.

### Steps To Reproduce
Command line:
```
# First initialize a new shared store and push it to an empty remote
gopass --yes setup --remote github.com/example/pass.git --alias example --create --name "John Doe" --email "john.doe@example.com"
```

### Expected behavior
Create a new sub store into my existing one with the provided remote git backend.

### Actual behavior
```
   __     _    _ _      _ _   ___   ___
 /'_ '\ /'_'\ ( '_'\  /'_' )/',__)/',__)
( (_) |( (_) )| (_) )( (_| |\__, \\__, \
'\__  |'\___/'| ,__/''\__,_)(____/(____/
( )_) |       | |
 \___/'       (_)

🌟 Welcome to gopass!
🌟 Initializing a new password store ...
❌ ⚠ Store is already initialized. Aborting.
```

### Environment
CLI 
gopass 1.12.4

**Comment by dominikschulz** [comment]
I'd argue this is working as intended. `gopass setup` is meant for the initial setup only.

Remove any existing stores before running that.

**Comment by dominikschulz** [comment]
But if you can provide a comprehensive description of your usecase, possible failure modes and expected behavior we could figure out if any of the existing commands supports that and it not how we could enable that.

Overall I guess you're trying to provide instructions /. Script for a fully automated gopass deployment? Is it for humans or machines (doesn't matter, just curious)?

So you want to add a mount or (re-) init the root store?

**Comment by jensklose** [comment]
You are right. That's my misinterpretation of the documentation. I need a solution for new team members.

Please close the issue.

**Comment by dominikschulz** [comment]
We can keep it open if you need more assistance.
I'm happy to help.

It's just that we didn't design the setup command for this specific use case (yet?)
