### ISSUE TITLE
Can auto push be disabled for team sharing store

### ISSUE THREAD

**Issue by morningspace** [gopasspw/gopass#1878]
### Summary

It looks the current gopass behavior is that it will auto sync all the time where there is a change. However, in a team sharing scenario, I'd like to control that only privilege member is allowed to push to the remote, while others can only pull.

It appears I can achieve this by configure Collaborators & teams on GitHub side, i.e. grant read only permission, but the gopass will still keep auto pushing w/ errors.

**Comment by dominikschulz** [comment]
Yes, this is true.

I have to admit I've never considered such a use case.

**Comment by morningspace** [comment]
Thanks @dominikschulz for your prompt reply. Any chance that it could be considered. I think it's a common case for team sharing. I haven't checked the gopass code, but if that's something kind of easy to add. I'd be happy to spend some time to add that.

**Comment by dominikschulz** [comment]
Maintaining config options is very tedious so I aim for as little config options as possible.

The AutoSync issue has been discussed before in #1567 and the general config handling approach in #1819 .
I understand your use case and I think this is something we could / should support, but I'm not yet sure what the least toilsome approach would be.

**Comment by dominikschulz** [comment]
To support the use case (i.e. a read only password store client) we would need:

* a use case description in `docs/usecases/` describing the use case
* a way to disable autosync-on-writes (maybe, read-only clients shouldn't even attempt to write to their store)
* changes to `gopass sync` to only pull, never push changes
* an integration test

Please note that we don't want to add new features without a clear usecase definition. Otherwise we'll accidentally break these in the future (this has happened a few times before, because nobody remembers why a specific feature was as it was).

**Comment by morningspace** [comment]
Sure, understood. What can I do or can help in this case? Maybe I can start w/ submitting a use case into `docs/usecases/`? Or if someone else should take that per the process.

> maybe, read-only clients shouldn't even attempt to write to their store
I think so. Since it's ready-only, there's no write and sync-on-write, but it needs pull to sync the remote changes from time to time.

@dominikschulz

**Comment by dominikschulz** [comment]
If you could contribute a use case definition that would help.

Then we can figure out what else we'd need.

**Comment by morningspace** [comment]
Sure, I will submit a PR later this week.

**Comment by morningspace** [comment]
PR #1892 ready for review. @dominikschulz

**Comment by AnomalRoil** [comment]
So, this would really require us to tackle #1567 as well, since this should probably be a per-store setting and not a global one, as said in your PR.

We've also discussed how we are handling configuration in #1819, please don't hesitate to chime in there to give your opinion, since you seem used to our advanced settings :) 

On my side, I think we should try and support this use-case, especially since Gopass is really aimed at team sharing too.

**Comment by morningspace** [comment]
Thanks @AnomalRoil , sure I will check #1567 and #1819.
