### ISSUE TITLE
gopass get should show command does not exist

### ISSUE THREAD

**Issue by warden** [gopasspw/gopass#1905]
### Summary

`gopass get` shows that a secret is not found which is misleading as this command does not exists at all.

### Steps To Reproduce

```
$ gopass get apikey
⚠ Entry "get" not found. Starting search...
[ 0] test1/apikey
[ 1] test2/apikey

Found secrets - Please select an entry (q to abort) [0]: 0
0
test1/apikey

Error: key not found in entry

$ gopass show apikey
⚠ Entry "apikey" not found. Starting search...
[0] test1/apikey
[1] test2/apikey

Found secrets - Please select an entry (q to abort) [0]:
0
test1/apikey
Secret: test1/apikey

*** ACTUAL SECRET VALUE ***


```

### Expected behavior

`gopass get` should render `gopass help`

### Environment

```
$ gopaas version
 gopass 1.12.5 (2021-03-27 22:25:42) go1.16.2 darwin amd64
<root>     - gpg 2.2.27 - git 2.31.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```

**Comment by AnomalRoil** [comment]
That a consequence of allowing to use of `gopass entryname` as a shortcut for `gopass show entryname`.

We could create a deny-list  of invalid commands that show the help, but where to stop? Not sure it's really needed.

**Comment by warden** [comment]
Well, if it's a shortcut then this is a bug as you can see it does not work.
It displayed the list of matching entries and even though 0 option was selected, it said the secret did not exist.

**Comment by dominikschulz** [comment]
No, this is working as intended.

I did try to remove this shortcut, that got a lot of backlash and then we agreed to keep the shortcut.

But that means we can't fix your issue.

**Comment by warden** [comment]
I'm sorry but I don't understand.

You are saying that it is shortcut for `gopass show entryname` - I just showed you above it does not work.
It seems to behave like it, but it does NOT find the secret, while when using `gopass show entryname` directly in the first place - THEN it works.

**Comment by AnomalRoil** [comment]
Yes, that's because `get` doesn't exist, it's not a shortcut.

The shortcut is using `gopass` alone. So here, what's happening is that `gopass` thinks your are running:
`gopass show get entryname`, so it is showing you the key "entryname" of the secret named "get", but you don't have any entry named "get" so it doesn't work.

**Comment by warden** [comment]
@AnomalRoil almost, but still wrong. Take a look at what exactly the output looks like.
- `gopass get whatever`
- it says: `⚠ Entry "get" not found. Starting search...` - that is fine
- then it **shows you a list of secrets it found and asks you for selection**
- then I select "enter" (or 0)

even though I selected an existing secret, it said secret not found - still a bug.

**Comment by AnomalRoil** [comment]
Actually no, look at the error it gave you at the end:
"Error: key not found in entry"
It didn't find the key "apikey" in the entry "test1/apikey" it used after
you chose it.

Run `gopass show get apikey` and you'll see it has the same behaviour.

Here is what gopass tries to do:
- it parses the input "get apikey", sees no known command since "get" is
not a command, so it uses the default "show" command, and runs "gopass show
get apikey" instead.
- "gopass show get apikey" is a command with a command, "show", followed by
an entryname "get", and an optional "key" parameter, to be able to use the
key-value feature. Here, since that optional parameters seems set to
"apikey", gopass will attempt to parse the content of your secret "get"
according to our doc:
https://github.com/gopasspw/gopass/blob/master/docs/commands/show.md#parsing-and-secrets
since gopass didn't find an entry named "get", it prompts you with an
interactive search, but it didn't forget about the fact that you requested
the value of the key-value named "apikey" in that entry, so once you
selected the "test1/apikey" entry instead of the "get" entry, gopass goes
on trying to access the value of the key "apikey" in that entry.
But since your entry does not contain a line with "apikey: something", it
fails to find the key "apikey" in that entry "test1/apikey" you selected,
and gives you the error message you had, saying it didn't find the key in
the entry.

>

**Comment by warden** [comment]
Wow... that's very unintuitive behaviour, at least for me. 
If you consider this to be 'as designed' then let it be, but I wouldn't be surprise when someone else has the same feeling as me in the future :-)

I appreciate your time and effort taken for your explanation though!

**Comment by AnomalRoil** [comment]
You should try using the key value feature, it is useful and it helps making sense of the behaviour:

```
gopass generate lets/test
gopass insert lets/test user
gopass generate lets/test recovery

gopass lets/test
gopass lets/test user
gopass show -C lets/test recovery
```

**Comment by dominikschulz** [comment]
My point is: I understand your confusion and was once trying to resolve that by removing the "shortcut", i.e. the implicit "show" when running `gopass <entry>`. But too many users complained that I backed off from that approach.

Unfortunately that means we'll have to keep the confusing status quo.

I'm not saying we can't improve the error messages. I'm happy to take suggestions on that. But the behaviour itself won't change (most likely).

**Comment by warden** [comment]
Sure, I get that, thanks a lot for the background. 
I actually was not aware of the key/value feature *inside* a secret (aka path) - and that *shortcut* transforms it silently to a lookup for key what is confusing.
No idea how to improve the message though..., the only thing I can think of is: ` Couldn't find key "get" in "test1/apikey"`
