### ISSUE TITLE
Feature: password expiration

### ISSUE THREAD

**Issue by waldauf** [gopasspw/gopass#1914]
At this time when you are not sure if some company had leaked user information is recommended to change the password after some time. Is there a possibility to add a password expiration feater?

In the file with a password will be the timestamp of the file change. If you use the file to invoke a password gopass looks at the timestamp and says if is after expiration. I know - there is a possibility to use the time of change file on the FS. But it can be changed during the copying process of the file.

It will be nice if gopass will replace the password but I think, it's not necessary. And better is to do it manually.

**Comment by dominikschulz** [comment]
`gopass audit` will already emit a warning about old passwords: https://github.com/gopasspw/gopass/blob/master/internal/audit/audit.go#L183

Not exactly what you want, but it goes somewhere in the right direction.

Also luckily for this we don't even need custom metadata since we usually can use the git history.

Beyond that I don't see how this could be made much more useful. Sure, you could add some more flexiblity but that comes at a pretty high maintenance cost. So I'd rather suggest to use `gopass audit`.

**Comment by waldauf** [comment]
@dominikschulz Thank you for your answer. I tried `gopass audit` and it works how I imagine. That's great. I have a few questions about it:

1. Is there a possibility to set the time of expiration in the command line? Now is hard set to 90 days.
2. How does work filter? In the gopass repository, I have also binary files and would like to skip them. I.e. according to a name with grep.  
3. Can I run the audit process just for checking the age of passwords?

**Comment by dominikschulz** [comment]
1. No, but I think we could add support for that.
2. It's path prefix. What you want isn't easily possible. Not sure if this is something I'd like to add.
3. No, but I think we could add support for that, too.
