### ISSUE TITLE
passage support

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2059]
@FiloSottile has released [passage](https://github.com/FiloSottile/passage) and I'd like to make our `age` implementation compatible to it as much as possible.

Mostly because I trust Filippo to a great length and his approach is probably sane.

Once age v1.1.0 comes with plugin support I'd like to support that, too. So people can use their hardware tokens (at least YubiKeys) with gopass+age.

**Comment by dominikschulz** [comment]
Notable changes I've found so far:
* IDFiles for age need to be renamed from `.age-ids` to `.age-recipients`
* The whole [`keyring.go`](https://github.com/gopasspw/gopass/blob/master/internal/backend/crypto/age/keyring.go) should go away. It will be replaced by a single identity file with (possibly) multiple password protected [identities](https://github.com/FiloSottile/age/blob/main/README.md?plain=1#L49)
* We should consider sourcing age identities from (or maybe even storing them to - not sure) `$HOME/.passage/identities`
* This one might get a bit messy, but maybe we can use `$HOME/.passage/store` as a fallback when not other store is defined and the age backend is selected.

**Comment by dominikschulz** [comment]
* `.age-ids` has been renamed
* `keyring.go` is mostly gone (except for backwards compatibility)

Next steps, if we choose to:
* Use passage identities
* Use passage store

**Comment by kfken** [comment]
This is great, thanks for adding this so quickly.  

To answer a question you had: I was using the previous age backend prior to your updates.  Everything seems to be working well since the changes you made to support passage.  

+1 vote for being fully compatible with age 1.1.  This branch (https://github.com/FiloSottile/age/tree/filippo/plugins) seems stable for use with age-plugin-yubikey; not sure what other changes might be in store for 1.1.
