### ISSUE TITLE
Fix flaky template tests

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2121]
https://github.com/gopasspw/gopass/pull/2117#issuecomment-1015261881

**Comment by AnomalRoil** [comment]
Example input that broke the test:

Running `md5crypt.Validate("foobar", s)` for `s` equal to:
```
{MD5-CRYPT}$1$?0$+??$HKyWvlSjUTJfUFAZXI5wt1
```

**Comment by AnomalRoil** [comment]
Okay, so broken down this is:

{MD5-CRYPT} -> prefix
$1$ -> magic
?0$+??  -> the salt
$ -> separator
HKyWvlSjUTJfUFAZXI5wt1 -> the hash encoded using 

But here the salt contains a `$` char.
So the problem probably comes from the `md5crypt.Validate` function which is splitting on `$`:

```
	if len(hash) < 15 || string(hash[0:14]) != "{MD5-CRYPT}$1$" {
		return false, ErrNotMd5cryptPassword
	}

	data := strings.Split(hash[14:], "$")

	newhash := crypt([]byte(password), []byte(data[0]))
``` 

Because then `data[0]` is just `?0` instead of being the whole salt.

So whenever we have a hash that contains `$` it will fail to validate properly.

**Comment by AnomalRoil** [comment]
Confirmed: https://go.dev/play/p/tr4BKz0sHh0
