### ISSUE TITLE
Symbols config options

### ISSUE THREAD

**Issue by Plexvola** [gopasspw/gopass#2151]
Since `usesymbols` got deprecated as an option, what is the standard way to make `gopass generate` generate a password with symbols by default ?

**Comment by AnomalRoil** [comment]
I guess you could set the env var `GOPASS_CHARACTER_SET` to explicitly define your character set, but then you need to unset it in order to have passwords without symbols, so it's not optimal probably.

Maybe the easiest way it to make an alias ? Like `alias gog='gopass generate -s'` or maybe `alias gopass-generate='gopass generate -s'`

**Comment by AnomalRoil** [comment]
Notice that in general websites that have known rules to require symbols or to not require them should be auto-detected by our code:
https://github.com/gopasspw/gopass/blob/757aa0847f7943044f4d5acac2e0b78140d0961b/internal/action/generate.go#L163-L171
and I think the env var is ignored in that case (unless used with --force after #2145, but that's only on master for now and not yet in a release.)

**Comment by dominikschulz** [comment]
With the new config system in place to should be easy to fix.
