### ISSUE TITLE
Feature request: configure default length

### ISSUE THREAD

**Issue by mcnesium** [gopasspw/gopass#2190]
Since [the `ji32k7au4a83` incident](https://duckduckgo.com/?q=ji32k7au4a83) I tend o use passwords with an odd number of characters, because I assume this can not happen then. gopass has a default length value set to `24` though:

    mcn@tx ~ gopass generate -c thismount/mysite/mylogin
    How long should the password be? [24]: 25

It would be cool to be able to set the default value to something else. Since I never found a setting therefore in the docs, I herewith kindly request this feature :)

PS: this is a copy of #1198 which sadly got auto-closed without any feedback.

**Comment by AnomalRoil** [comment]
I guess we're trying to avoid adding new config options as much as possible but might maybe consider adding a env variable...

BTW, do you know that you can also specify the length directly when writing the first cmd?

```
gopass generate -c thismount/mysite/mylogin 25
```
will directly generating a 25 char password, skipping the prompt.

**Comment by mcnesium** [comment]
> I guess we're trying to avoid adding new config options as much as possible but might maybe consider adding a env variable...

an env var would be great.

> BTW, do you know that you can also specify the length directly when writing the first cmd?

Yes I do, but doing so will make very good bash feature `escape-period` that repeats the last argument not return the password path but the number. This is inconvenient, when you want to run another command on that same path, for example edit the password entry after creating it or copy it to the clipboard again, etc. Imho the password path should always be the last argument.

**Comment by dotcs** [comment]
I'd like to work on this, if possible! I'm first time contributor to this project. Unfortunately currently no issues are available that have the [help-wanted](https://github.com/gopasspw/gopass/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) label, so why not work on this one? ;)

I would like to introduce a env variable `GOPASS_PW_DEFAULT_LENGTH` that can be used to overwrite the hard-coded default length. If this variable is set, it is used instead of `const defaultLength = 24`, if not the old value is used as a fallback.

Usage: `GOPASS_PW_DEFAULT_LENGTH=25 gopass generate -c thismount/mysite/mylogin`

I've [already worked on this change](https://github.com/gopasspw/gopass/compare/master...dotcs:feature/default-length-env?expand=1) on my fork but am not sure if I already should open the PR since I'm lacking tests at the moment and also don't know if I should put the `defaultLengthFromEnv` fn somewhere else, because I think we would also need it in the [wizard](https://github.com/gopasspw/gopass/blob/d51b84bda7cc54d9caa761074e4e0dedfcdcc098/internal/create/wizard.go#L29) that is part of the `create` package. Should I just duplicate the function or should I move it somewhere else? Any other comments on my changes so far?

**Comment by dotcs** [comment]
I've opened a PR for this. Because I'm not sure if this approach should also be used in the wizard and since it's unclear to me how to write tests for the wizard, I focused only on the `generate` subcmd. Hope this is okay.

**Comment by dotcs** [comment]
I agree with this opinion, @AnomalRoil. Thanks for your feedback. I've added a commit to my PR that changes this behavior. Please have another look at the PR.

**Comment by mcnesium** [comment]
@dotcs thank you very much for your effort. Works like a charm :tada:
