### ISSUE TITLE
Help to understand why decypt on second machine fails

### ISSUE THREAD

**Issue by brendan-pike** [gopasspw/gopass#2214]
Feel free to delete and tell me where this is more appropriate.

I'm a long time basic level user (started on pass) but I'm unable to get gopass to decrypt on a second machine (laptop).  I've added recipient keys, re-synced, cloned the repository, I can list fine but decrypt times out.   I believe that my laptop is trying to use the original key to decrypt , ie. `gpg: public key is A2445E3917BBC105
gpg: using subkey A2445E3917BBC105 instead of primary key A2592C4C8D608EFB
` which the laptop does not have.
If I try directly, gpg -v -d /path-to-a-key.gpg it just times out with "decryption failed: No secret key"

How do I debug what it going wrong, why is it not using the secret key is had access to?

**Comment by dominikschulz** [comment]
Trying directly with `gpg` is a very good idea. This already shows that the problem is likely not a bug (at least not on the second machine - might still be an issue with not using proper keys on the first machine).

On the first machine (i.e. the one where it works) you could try running `gopass fsck --decrypt` and then `gopass sync`. Maybe that helps.

Otherwise we'll need to dig deeper into what `gpg` is doing.

**Comment by brendan-pike** [comment]
thanks Dominik, I worked out that gpg did not know the password and was not asking for it, maybe it never had one? In any case I just destroyed that sig and created a new one and all is well now :)
