### ISSUE TITLE
[FR] age with YubiKeys

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2260]
[age plugin support](https://github.com/FiloSottile/age/releases/tag/v1.1.0-rc.1) is coming along nicely and I'd love to have gopass ready and tested with YKs once 1.1.0 final is released.

Will try to give it a try to iron out potential issues and write down any specifics in our docs.

**Comment by dominikschulz** [comment]
This will have to wait until age 1.1.0 is finally released.

**Comment by dominikschulz** [comment]
There we go: https://github.com/FiloSottile/age/releases/tag/v1.1.0 🥳

**Comment by AnomalRoil** [comment]
`age` as a library doesn't work well with Yubikeys for now.

Related discussion:
https://github.com/FiloSottile/age/discussions/480

**Comment by MarkusZoppelt** [comment]
> `age` as a library doesn't work well with Yubikeys for now.

This might change if the changes by @gdbinit make it upstream:
https://github.com/gdbinit/age / https://github.com/gdbinit/yage

**Comment by fredfoss** [comment]
Hey Dominik, I was wondering if there is any progress on this feature or plans for it? There is a yubikey plugin now for age/rage, <https://github.com/str4d/age-plugin-yubikey>, which is also possible to use with [passage](https://github.com/FiloSottile/passage). From README:

```
Example: set up with age-plugin-yubikey
---------------------------------------

This setup requires age v1.1.0, or rage (https://github.com/str4d/rage), and
the PIV plugin age-plugin-yubikey (https://github.com/str4d/age-plugin-yubikey).

It's recommended to add more YubiKeys and/or age keys to the .age-recipients
file as recovery options, in case this YubiKey is lost.

    age-plugin-yubikey # run interactive setup
    age-plugin-yubikey --identity >> $HOME/.passage/identities
    age-plugin-yubikey --list >> $HOME/.passage/store/.age-recipients
```

I'm not sure because I can't find back to where I read it, but I think the age author said the yubikey stuff would stay a plugin, and not be integrated. Same with pinentry stuff, but rage comes with it though in some form. But worth to note the yubikey plugin is in Rust ¯\\\_(ツ)\_/¯

**Comment by con-f-use** [comment]
The age plugin seems to require PIV-enabled yubikeys, which for instance, seems to rule out the yubikey bio series. It would be nice to find a way to use the bio series for pin-entry to gopass, too.
