### ISSUE TITLE
Feature: allow setting autosync.interval in minutes

### ISSUE THREAD

**Issue by quite** [gopasspw/gopass#2730]
It would be useful to be able to set autosync interval with greater granularity. I think minutes could be enough, seconds won't be needed.

To be backwards compatible, we'd move the setting to a string, and still interpret a clean number as days, but accept an `m` suffix for interpreting the number as minutes.

**Comment by AnomalRoil** [comment]
Autosync isn't run in the background when used in REPL mode, or is it?

Because iiuc it's run before another command if delay has passed, and optionally if set to 0, it's run every time a command is run, no?

So to me, having a granularity below a day is not really better than setting it to 0, no?

Or am o

**Comment by quite** [comment]
Yes granularity of for example hours (or minutes, for completeness) would be much better than days. Consider that you may be showing/inserting a lot of passwords throughout the day, while (physically) moving between installations of gopass. Having for example `120m` would be much better than `0`, which would result in tedious sync all the time. Or `1` (day) which in this use-case would result in a number of merge conflicts.
