### ISSUE TITLE
Inconsistency for newlines

### ISSUE THREAD

**Issue by antoyo** [gopasspw/gopass#788]
Hi.
I have an issue with `msmtp` which requires me to add `; echo` at the end of `passwordeval "gopass show -f mail"`, otherwise, I get the following error:
```
msmtp: output of 'gopass show -f mail' is longer than 500 characters, or is not terminated by newline
```
I think it's because [the newline is not output when it's not in a tty](https://github.com/justwatchcom/gopass/blob/master/pkg/action/show.go#L127).
I think it would be better to have a consistent behavior to avoid this issue.
Thanks.

**Comment by dragon788** [comment]
If you use `gopass show -o mail` instead of `-f` does it give the same message?

**Comment by antoyo** [comment]
Same message with `-o`.

**Comment by dragon788** [comment]
Is this a password/passphrase secret that is really over 500 characters or an RSA key or something similar?

**Comment by antoyo** [comment]
@dragon788 No, it is less than 30 characters.
And it works with:
```
gopass show -f mail; echo
```
so it is really a newline issue.

**Comment by dragon788** [comment]
What version of `gopass` are you using, the Ubuntu PPA or the 18.04 Universe version or `go get github.com/justwatchcom/gopass` ?

**Comment by antoyo** [comment]
The one on ArchLinux community repository, so 1.6.11.

**Comment by dragon788** [comment]
Interesting, that commit also exists in 1.6.10 that I'm using and I haven't encountered that issue with long or short passwords yet.

If you pass `msmtp` the flag `--passwordeval=$(gopass show -o mail)` instead of defining it in the config file does the application open correctly or are you starting it from a startup script which is why you need it in the config file?

I definitely agree the lines you pointed out could be problematic, I'm just curious what behavior is triggering it.

**Comment by antoyo** [comment]
Same error when passing this flag.
I use a config file for convenience.

**Comment by antoyo** [comment]
So, what are you unable to reproduce?

**Comment by gpanders** [comment]
I am having the exact same issue with `msmtp` and would like for this issue not to be closed.

**Comment by dominikschulz** [comment]
Yes, I'm able to reproduce it. The fix is easy, but I'm still considering what else might break by fixing this issue.

**Comment by antoyo** [comment]
Any news on this issue?

**Comment by sigio** [comment]
Also have this issue with gopass 1.8.5 (dd169b82e713c09f31fa6919342543163b5894f3) go1.12 linux amd64

After creating a file with a password, some newlines, and some other data in it... gopass (or pass) then returns the contents without all the empty lines, and without the newline at the end.

**Comment by elias5000** [comment]
I ran into this issue when decrypting multi-line payloads that deliberately contain empty lines. For these kind of secrets gopass is broken in the current state.
I would greatly appreciate if this issue would get some priority.

**Comment by dominikschulz** [comment]
This should be mostly covered by #1310.
However we still need to look at (read: remove) the special handling when printing the secret content.

**Comment by AnomalRoil** [comment]
@dominikschulz What is the expected behaviour? I could take a look at it :)

**Comment by dominikschulz** [comment]
Thanks!

The secret content handling has changed quite a bit since this was reported.

* First we'd need to verify this still applies (it might be fixed, I didn't check recently).
* Then we should agree on the expected behaviour.
* And we need to ensure the expected behaviour is caught by a test case.
* And change it if it's not behaving as expected right now (this will likely be a 1-2 character change in [show.go](https://github.com/gopasspw/gopass/blob/master/internal/action/show.go#L132)

In general I'd like to support storing and retrieving unaltered content in gopass secrets.
For retrieving specific values, like the password I'm not so sure.
Also I don't remember why we introduced the special handling for newlines in a TTY right now.
I think this was due to the old binary support (but that's gone / change by now, too).

**Comment by AnomalRoil** [comment]
It seems there are some (potentially new) issues with the handling of new lines, some times it will remove all new lines and display the rest of the entry on a single line and sometimes it won't. I am still to identify when it does what.   
But it seems related to the combinations of flags along with the `show` command.

**Comment by dominikschulz** [comment]
Thanks for your efforts. I will try to formalize your findings into a proper feature documentation.
