### ISSUE TITLE
Name confusion

### ISSUE THREAD

**Issue by amc90** [gopasspw/gopass#854]
I know this isn't a software bug as such, so please forgive me if this is inappropriate.

I heard there was a go client, so I ended up installing it with apt-get , which of course got me https://github.com/aviau/gopass . I decided against it. Then I heard that there was another gopass, so I looked at https://www.passwordstore.org/ and found https://github.com/cortex/gopass

It was only by a fluke that I realised that there was a third gopass.

I've been using the original pass, qtpass, and the android client for several years, and I've played with some of the other clients too. This is the best client out there. I'm sure other people have missed out on it entirely due to naming confusion.

Have you considered a rename?

**Comment by dominikschulz** [comment]
Thanks for asking.

The name clash with the "other" gopass in Debian is unfortunate. Especially since it's a very similar project with a completely different feature set. It get's even more confusing if you look at the distros that include "our" gopass as a package.

When choosing the name only knew about github.com/howeyc/gopass (which is something quite different) and https://github.com/cortex/gopass (which was already deprecated back then).

Right now I can't really imagine renaming this project, IMHO this would create even more confusion.
We tried to avoid the confusion around the gopass in Debian by talking to the maintainer but unfortunately that got us nowhere.

**Comment by amc90** [comment]
I can imagine that it would create confusion, yes.

Perhaps appending a suffix to the project name (but leaving the binary and documentation and so on the same) is an option?

Anyway, thanks for the software.

**Comment by anarcat** [comment]
>  We tried to avoid the confusion around the gopass in Debian by talking to the maintainer but unfortunately that got us nowhere.

Could you expand on the process which you followed here?

There are various mechanisms in Debian to work around duplicate package names and it should be possible to have both software shipped in Debian, with some compromise.

For example, @aviau's gopass could be named "gopass-aviau" and this one could be "gopasspw" and both would install a "gopass" binary and conflict with each other... the only downside is that `apt install gopass` would prompt you to choose which binary instead of picking one for you...

**Comment by anarcat** [comment]
> I've been using the original pass, qtpass, and the android client for several years, and I've played with some of the other clients too. This is the best client out there.

@amc90 could you expand on why you think this is the best client? just curious. :)

**Comment by aviau** [comment]
> Could you expand on the process which you followed here?

I was contacted personally and asked to remove my package from the Debian archive. I said no and suggested that they find another name if they wanted to avoid confusion.

It looks like @dominikschulz also thought that I packaged my project as a reaction to the release of his, but it was not the case.

Here are some of the elements of my reponses:

```
I packaged gopass for Debian in July 2017, well before you made your
repository public.

[...]

See the original upload message:
 - https://packages.qa.debian.org/g/gopass/news/20170719T070012Z.html

The Intend to Package bug that I opened in 2015:
 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781494
```

> For example, @aviau's gopass could be named "gopass-aviau" and this one could be "gopasspw" and both would install a "gopass" binary and conflict with each other... 

Yeah, there are a number of ways to fix this but I wouldn't hastily rename my package before there is another one available in the archive. Someone can just upload a gopass-pw that conflicts with mine.

**Comment by cara380nm** [comment]
@anarcat The mountpoint thing is a slick way of handling multiple repositories. Multiple recipients seem to actually work in practice. Fsck will pick up an incorrect recipient list. The password checker thing is nice too. The gopassbridge browser plugin is actually better than the GUIs I've played with in some respects (the only thing it is missing is free-text).

I like go based applications - they seem to be quite self contained and simple to manage outside of distribution packages, so if I need to distribute it I may be able to get away with puppet copying a binary.

**Comment by anarcat** [comment]
did that bot just mark the issue as stale because it wasn't active since it last marked it as stale? that's frigging annoying...

**Comment by anarcat** [comment]
god i hate that bot :)

**Comment by aviau** [comment]
FYI given that my project is no longer maintained I filed a Debian Bug to remove it here:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1108303

**Comment by dominikschulz** [comment]
@aviau Thank you very much for letting us know. I would love to resolve this source of confusion!
