### ISSUE TITLE
Enhance auto completion

### ISSUE THREAD

**Issue by nilskuhn** [gopasspw/gopass#926]
### Summary

Auto-completion of `show` command is not very clear and helpful at the moment if one uses a large password store or even multiple stores with hundreds of entries. At the moment completion just lists all secrets at once.

### Steps To Reproduce

Just type `gopass show` and hit TAB key.

![image](https://user-images.githubusercontent.com/1001134/45546922-348db800-b81f-11e8-978a-1d5fa7d9cfcd.png)

### Expected behavior

For me it would be much more helpful if it would work like bash auto completion for filesystem (e.g. using `ls`). Auto-completion should just take the next path hierarchy into account for auto completion.

If auto completion would take arbitrary parts of the next path hierarchy into account, like `zsh` auto completion for filesystem that would be even better:

![gopass_evenbetterautocompletion](https://user-images.githubusercontent.com/1001134/45547418-0c9f5400-b821-11e8-9847-ec68d69c33c5.gif)

**Comment by metalmatze** [comment]
This works for me as you have described.
I think the difference in your issue between what you do in `Steps to Reproduce` and `Expected behavior` is that you don't put some prefix after `gopass show` but you start with `ls pkg`.

The behavior for gopass and ls autocompletion for me is exactly the same. If I don't put anything behind `ls` or `gopass show` it will basically print everything. Once I add a prefix for a path, only secrets with that prefix path are shown.

**Comment by nilskuhn** [comment]
But `ls` won't show all subfolders recursively. gopass' `show`command does exactly that.

**Comment by metalmatze** [comment]
Ah, ok. That's what you're going for.
I guess we can improve this then. Do you want to create a PR for this @nilskuhn?

**Comment by nilskuhn** [comment]
Yes, I would like to. 

Could you give me a hint which packages/files should be affected? Or is there some documentation of package structure?

**Comment by metalmatze** [comment]
The CLI helper start for list (ls) in here:
https://github.com/gopasspw/gopass/blob/master/commands.go#L731
https://github.com/gopasspw/gopass/blob/master/pkg/action/list.go#L25:18

I think you need to look into list, because that is what the autocompletion is using in the background (even for other commands like show).

**Comment by dominikschulz** [comment]
@metalmatze That's correct, but we shouldn't need to change list for this change.

I think it should be possible to implement this change in [´action.Complete´](https://github.com/gopasspw/gopass/blob/master/pkg/action/completion.go#L29). 
You can inspect [`c.Args()`](https://godoc.org/github.com/urfave/cli#Context.Args) and filter the list output there.
