### ISSUE TITLE
No useable private keys found

### ISSUE THREAD

**Issue by sevenmaxis** [gopasspw/gopass#960]
```
$ gpg -K
/home/megas/.gnupg/pubring.kbx
------------------------------
sec   rsa4096 2018-10-15 [SC] [expires: 2023-10-14]
      5A5E5D9XXXX4B5F93F01XXXX8CE297B6C1854
uid           [ unknown] MyName <email>
ssb   rsa4096 2018-10-15 [E] [expires: 2023-10-14]
```

```
$ gopass
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: Y
[init] [local] Initializing your local store ...

Error: failed to run onboarding wizard: failed to init local store: failed to read user input: no useable private keys found
```

The gpg key was imported from another computer.

**Comment by martinhoefling** [comment]
I suspect that the trust is not set correctly for the key. Trust levels full or ultimate should work afair.

**Comment by sevenmaxis** [comment]
You're right, I changed the trust level to ultimate and gopass accepted this key

**Comment by Kraymer** [comment]
Just had same problem, it fixed  it.

Would be nice if the error message in the CLI pointed to that direction

**Comment by espoelstra** [comment]
For those arriving here and still running into this issue, maybe with a Keybase account and/or a Yubikey, if you have several public keys that have been uploaded to Keybase or another keyserver using the same email address but some of them have expired, if you do `gpg --edit-key yourEmail@domain` `gpg>trust` `5` (for ultimate) you are probably NOT editing the correct key. After you run `gpg --card-edit` `gpg> fetch` (if you have a Yubkey and uploaded to Keybase), you need to run `gpg --list-secret-keys` and using the portion after the `0x` of the UNEXPIRED/currently valid key (`sec#` if using a Yubikey or in `gpg --list-keys` after the `0x` in the pub line), then run `gpg --edit-key 0123456789ABCDEF` and run `gpg> trust` `5` on this specific key, and you shouldn't get the error anymore.

Oddly enough I was able to use the GPG key for SSH and Git cloning by just trusting the email address, but in order to get `gopass` to like it I had to specify the correct key and trust it specifically.

**Comment by pmyjavec** [comment]
Just hit this issue. It's a very confusing error.
